import { AdminCard, AdminHeading, Field, Input, SubmitButton } from "@/components/admin/ui";
import { checkWhatsAppStatusAction, sendWhatsAppTestAction } from "./actions";
export const dynamic = "force-dynamic";
export default async function WhatsAppTestPage({ searchParams }: { searchParams: Promise<{ sent?: string; checked?: string; sid?: string; status?: string; code?: string; message?: string; error?: string }> }) {
  const { sent, checked, sid, status, code, message, error } = await searchParams;
  const delivered = status === "delivered" || status === "read";
  const failed = status === "failed" || status === "undelivered";
  return <><AdminHeading title="WhatsApp Test" />
    {sent && <div className="mb-4 rounded-lg border border-line bg-ink-card px-4 py-3 text-sm text-muted"><p>Twilio accepted the request{status ? ` with initial status “${status}”` : ""}. This is not yet delivery confirmation.</p>{sid && <form action={checkWhatsAppStatusAction} className="mt-3"><input type="hidden" name="sid" value={sid} /><SubmitButton>Check delivery status</SubmitButton></form>}</div>}
    {checked && <div className={`mb-4 rounded-lg border px-4 py-3 text-sm ${delivered ? "border-ok/40 bg-ok/10 text-ok" : failed ? "border-bad/40 bg-bad/10 text-bad" : "border-line bg-ink-card text-muted"}`}><p>Twilio delivery status: <strong>{status ?? "unknown"}</strong>{code ? ` (error ${code})` : ""}.</p>{message && <p className="mt-1">{message}</p>}{!delivered && !failed && sid && <form action={checkWhatsAppStatusAction} className="mt-3"><input type="hidden" name="sid" value={sid} /><SubmitButton>Check again</SubmitButton></form>}</div>}
    {error === "phone" && <p className="mb-4 rounded-lg border border-bad/40 bg-bad/10 px-4 py-2 text-sm text-bad">Enter a valid WhatsApp number with country code, for example +91XXXXXXXXXX.</p>}
    {error === "send" && <p className="mb-4 rounded-lg border border-bad/40 bg-bad/10 px-4 py-2 text-sm text-bad">Twilio could not submit the test. {message || "Check the server logs and Twilio setup."}</p>}
    {error === "status" && !checked && <p className="mb-4 rounded-lg border border-bad/40 bg-bad/10 px-4 py-2 text-sm text-bad">Could not check Twilio delivery status. {message}</p>}
    <AdminCard title="Send dummy booking notification"><form action={sendWhatsAppTestAction} className="max-w-xl space-y-4"><Field label="Recipient WhatsApp number" hint="Use E.164 format, e.g. +91XXXXXXXXXX. Sandbox recipients must first join your Twilio Sandbox."><Input name="recipient" type="tel" required placeholder="+91XXXXXXXXXX" /></Field><div className="rounded-lg border border-line bg-ink p-4 font-mono text-sm leading-6 text-muted"><p className="font-sans text-xs font-semibold uppercase tracking-wider text-fg">Dummy booking message</p><p className="mt-2">Name: John Doe<br />Phone: +91XXXXXXXXXX<br />Date: 20 July<br />Time: 6:00 PM<br />Email: john@email.com</p></div><p className="text-xs text-muted/70">The Twilio Content Template must use this same five-field body format; its configured header will appear above it.</p><SubmitButton>Send test WhatsApp</SubmitButton></form></AdminCard></>;
}
